In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn import svm
from sklearn.metrics import  accuracy_score

In [2]:
df = pd.read_csv('/content/diabetes.csv')

In [3]:
df.head()

Pregnancies  Glucose  BloodPressure  ...  DiabetesPedigreeFunction  Age  Outcome
0            6      148             72  ...                     0.627   50        1
1            1       85             66  ...                     0.351   31        0
2            8      183             64  ...                     0.672   32        1
3            1       89             66  ...                     0.167   21        0
4            0      137             40  ...                     2.288   33        1

[5 rows x 9 columns]

In [4]:
df.shape

(768, 9)

In [5]:
df.describe()

Pregnancies     Glucose  ...         Age     Outcome
count   768.000000  768.000000  ...  768.000000  768.000000
mean      3.845052  120.894531  ...   33.240885    0.348958
std       3.369578   31.972618  ...   11.760232    0.476951
min       0.000000    0.000000  ...   21.000000    0.000000
25%       1.000000   99.000000  ...   24.000000    0.000000
50%       3.000000  117.000000  ...   29.000000    0.000000
75%       6.000000  140.250000  ...   41.000000    1.000000
max      17.000000  199.000000  ...   81.000000    1.000000

[8 rows x 9 columns]

In [6]:
df['Outcome'].value_counts()

Outcome
0    500
1    268
Name: count, dtype: int64

In [7]:
df.groupby('Outcome').mean()

Pregnancies     Glucose  ...  DiabetesPedigreeFunction        Age
Outcome                           ...                                     
0           3.298000  109.980000  ...                  0.429734  31.190000
1           4.865672  141.257463  ...                  0.550500  37.067164

[2 rows x 8 columns]

In [8]:
x = df.drop(columns='Outcome', axis=1)
y = df['Outcome']

In [9]:
x

Pregnancies  Glucose  BloodPressure  ...   BMI  DiabetesPedigreeFunction  Age
0              6      148             72  ...  33.6                     0.627   50
1              1       85             66  ...  26.6                     0.351   31
2              8      183             64  ...  23.3                     0.672   32
3              1       89             66  ...  28.1                     0.167   21
4              0      137             40  ...  43.1                     2.288   33
..           ...      ...            ...  ...   ...                       ...  ...
763           10      101             76  ...  32.9                     0.171   63
764            2      122             70  ...  36.8                     0.340   27
765            5      121             72  ...  26.2                     0.245   30
766            1      126             60  ...  30.1                     0.349   47
767            1       93             70  ...  30.4                     0.315   23

[768 rows x 8 columns]

In [10]:
y

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64

In [11]:
scaler = StandardScaler()

In [12]:
scaler.fit(x)

StandardScaler()

In [14]:
x = scaler.transform(x)

In [16]:
x

array([[ 0.63994726,  0.84832379,  0.14964075, ...,  0.20401277,
         0.46849198,  1.4259954 ],
       [-0.84488505, -1.12339636, -0.16054575, ..., -0.68442195,
        -0.36506078, -0.19067191],
       [ 1.23388019,  1.94372388, -0.26394125, ..., -1.10325546,
         0.60439732, -0.10558415],
       ...,
       [ 0.3429808 ,  0.00330087,  0.14964075, ..., -0.73518964,
        -0.68519336, -0.27575966],
       [-0.84488505,  0.1597866 , -0.47073225, ..., -0.24020459,
        -0.37110101,  1.17073215],
       [-0.84488505, -0.8730192 ,  0.04624525, ..., -0.20212881,
        -0.47378505, -0.87137393]])

In [17]:
X_train, X_test, Y_train, Y_test = train_test_split(x, y, test_size=0.2, stratify=y, random_state=2)

In [18]:
X_train

array([[-1.14185152, -0.05929342, -3.57259724, ...,  0.05170968,
        -0.9992857 , -0.78628618],
       [ 0.63994726, -0.49745345,  0.04624525, ..., -0.15136112,
        -1.05666795,  0.31985461],
       [-0.84488505,  2.13150675, -0.47073225, ..., -0.24020459,
        -0.2231152 ,  2.19178518],
       ...,
       [ 2.12477957, -1.12339636,  0.25303625, ..., -0.24020459,
        -0.51908683,  0.14967911],
       [ 0.04601433, -0.27837344,  0.45982725, ...,  0.94014439,
        -0.71237443,  0.40494237],
       [-1.14185152, -1.09209922, -0.05715025, ...,  0.48323511,
        -0.70633419, -0.70119842]])

In [20]:
X_test

array([[-0.25095213, -0.46615631,  0.14964075, ..., -0.78595734,
        -0.79995787, -0.53102292],
       [-0.25095213, -0.24707629, -1.29789624, ..., -1.21748278,
        -1.00230582, -0.95646168],
       [ 0.3429808 ,  0.81702665,  0.45982725, ...,  0.2167047 ,
        -0.76673656,  2.7023117 ],
       ...,
       [-0.54791859, -0.34096773,  0.25303625, ...,  0.05170968,
         0.6829204 , -0.53102292],
       [-0.54791859, -1.24858494,  0.14964075, ..., -0.24020459,
         0.22688248, -0.70119842],
       [ 2.7187125 , -0.46615631,  0.14964075, ...,  0.58477051,
        -0.88754131,  1.00055664]])

In [21]:
Y_train

619    1
329    0
13     1
476    1
45     1
      ..
303    1
592    1
559    0
725    0
253    0
Name: Outcome, Length: 614, dtype: int64

In [22]:
Y_test

615    0
80     0
148    0
132    1
501    0
      ..
127    0
185    1
85     0
497    0
86     0
Name: Outcome, Length: 154, dtype: int64

In [23]:
model = svm.SVC(kernel='linear')

In [24]:
model.fit(X_train, Y_train)

SVC(kernel='linear')

In [25]:
# accuracy on training data
X_train_prediction = model.predict(X_train)
score = accuracy_score(X_train_prediction, Y_train)
print("Accuracy score for training data", score)

Accuracy score for training data 0.7866449511400652


In [26]:
# accuracy on test data
X_test_prediction = model.predict(X_test)
score = accuracy_score(X_test_prediction, Y_test)
print("Accuracy score for test data", score)

Accuracy score for test data 0.7727272727272727


In [28]:
#making prediction
input = (2,197,70,45,543,30.5,0.158,53)

input_np_array = np.asarray(input)

input_reshaped = input_np_array.reshape(1, -1)

std_data = scaler.transform(input_reshaped)

prediction = model.predict(std_data)
print(prediction)

if(prediction[0]==0):
  print("The person is not diabetic")
else:
  print("The person is diabetic")

[1]
The person is diabetic


/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
