In [1]:
import pandas as pd
import numpy as np
import re
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import  accuracy_score

In [2]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [4]:
print(stopwords.words('english'))

['a', 'about', 'above', 'after', 'again', 'against', 'ain', 'all', 'am', 'an', 'and', 'any', 'are', 'aren', "aren't", 'as', 'at', 'be', 'because', 'been', 'before', 'being', 'below', 'between', 'both', 'but', 'by', 'can', 'couldn', "couldn't", 'd', 'did', 'didn', "didn't", 'do', 'does', 'doesn', "doesn't", 'doing', 'don', "don't", 'down', 'during', 'each', 'few', 'for', 'from', 'further', 'had', 'hadn', "hadn't", 'has', 'hasn', "hasn't", 'have', 'haven', "haven't", 'having', 'he', "he'd", "he'll", 'her', 'here', 'hers', 'herself', "he's", 'him', 'himself', 'his', 'how', 'i', "i'd", 'if', "i'll", "i'm", 'in', 'into', 'is', 'isn', "isn't", 'it', "it'd", "it'll", "it's", 'its', 'itself', "i've", 'just', 'll', 'm', 'ma', 'me', 'mightn', "mightn't", 'more', 'most', 'mustn', "mustn't", 'my', 'myself', 'needn', "needn't", 'no', 'nor', 'not', 'now', 'o', 'of', 'off', 'on', 'once', 'only', 'or', 'other', 'our', 'ours', 'ourselves', 'out', 'over', 'own', 're', 's', 'same', 'shan', "shan't", 'she

In [5]:
df = pd.read_csv('/content/train.csv')

In [6]:
df.head()

id  ... label
0   0  ...     1
1   1  ...     0
2   2  ...     1
3   3  ...     1
4   4  ...     1

[5 rows x 5 columns]

In [7]:
df.shape

(20800, 5)

In [8]:
df.isnull().sum()

id           0
title      558
author    1957
text        39
label        0
dtype: int64

In [9]:
# Filling the missing values
df = df.fillna(' ')

In [10]:
df.isnull().sum()

id        0
title     0
author    0
text      0
label     0
dtype: int64

In [11]:
df['Content'] = df['author'] + ' ' + df['title']

In [12]:
df.head()

id  ...                                            Content
0   0  ...  Darrell Lucus House Dem Aide: We Didn’t Even S...
1   1  ...  Daniel J. Flynn FLYNN: Hillary Clinton, Big Wo...
2   2  ...  Consortiumnews.com Why the Truth Might Get You...
3   3  ...  Jessica Purkiss 15 Civilians Killed In Single ...
4   4  ...  Howard Portnoy Iranian woman jailed for fictio...

[5 rows x 6 columns]

In [13]:
port_stem = PorterStemmer()

In [14]:
def stemming(content):
  regX = re.sub('˄a-zA-Z', ' ', content)
  lower_content = regX.lower()
  splitted_content = lower_content.split()
  stemming_content = [port_stem.stem(word) for word in splitted_content if not word in stopwords.words('english')]
  stemmed_content = ' '.join(stemming_content)
  return stemmed_content

In [15]:
df['Content'] = df['Content'].apply(stemming)

In [16]:
df['Content']

0        darrel lucu hous dem aide: didn’t even see com...
1        daniel j. flynn flynn: hillari clinton, big wo...
2                  consortiumnews.com truth might get fire
3        jessica purkiss 15 civilian kill singl us airs...
4        howard portnoy iranian woman jail fiction unpu...
                               ...                        
20795    jerom hudson rapper t.i.: trump ’poster child ...
20796    benjamin hoffman n.f.l. playoffs: schedule, ma...
20797    michael j. de la merc rachel abram macy’ said ...
20798    alex ansari nato, russia hold parallel exercis...
20799                         david swanson keep f-35 aliv
Name: Content, Length: 20800, dtype: object

In [17]:
x = df['Content'].values
y = df['label'].values


In [18]:
x.shape

(20800,)

In [19]:
y

array([1, 0, 1, ..., 0, 1, 1])

In [21]:
# Converting text into numerical values
vectorizer = TfidfVectorizer()
vectorizer.fit(x)
x = vectorizer.transform(x)

In [23]:
print(x)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 218021 stored elements and shape (20800, 21822)>
  Coords	Values
  (0, 809)	0.3646500188253278
  (0, 3403)	0.33756896138985654
  (0, 3952)	0.2266469969205269
  (0, 4763)	0.33044571153796654
  (0, 4995)	0.2512923264945339
  (0, 5256)	0.27468869329117757
  (0, 6433)	0.21422587910261737
  (0, 8832)	0.20534182453318398
  (0, 9692)	0.22757176689298134
  (0, 10747)	0.26822209263186303
  (0, 11072)	0.33384522056560495
  (0, 16473)	0.23676064517956455
  (0, 19097)	0.27315635150958634
  (1, 2258)	0.2928176012009572
  (1, 2713)	0.15460118725006144
  (1, 3100)	0.3870784468942128
  (1, 3778)	0.19062686807106288
  (1, 4728)	0.26268668599849243
  (1, 7101)	0.711483310803025
  (1, 8608)	0.19815023888659125
  (1, 20416)	0.29951908908156866
  (2, 3933)	0.31669937181571
  (2, 4162)	0.4602325600950218
  (2, 6968)	0.39293503470255664
  (2, 7650)	0.34605253138342823
  :	:
  (20797, 8874)	0.21736692401926294
  (20797, 10431)	0.22258731789449554
 

In [24]:
X_train, X_test, Y_train, Y_test = train_test_split(x, y, test_size=0.2, stratify=y, random_state=2)

In [25]:
X_train.shape

(16640, 21822)

In [26]:
X_train

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 174179 stored elements and shape (16640, 21822)>

In [27]:
X_test

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 43842 stored elements and shape (4160, 21822)>

In [28]:
Y_train

array([0, 0, 0, ..., 0, 0, 1])

In [29]:
Y_test

array([1, 0, 1, ..., 1, 1, 0])

In [31]:
model = LogisticRegression()

model.fit(X_train,Y_train)

LogisticRegression()

In [32]:
# accuracy on training data
X_train_prediction = model.predict(X_train)
score = accuracy_score(X_train_prediction, Y_train)
print("Accuracy score for training data", score)

Accuracy score for training data 0.9865985576923076


In [33]:
# accuracy on test data
X_test_prediction = model.predict(X_test)
score = accuracy_score(X_test_prediction, Y_test)
print("Accuracy score for test data", score)

Accuracy score for test data 0.9774038461538461


In [35]:
# Making predictions
X_new = X_test[1]

prediction = model.predict(X_new)

if(prediction[0] == 0):
  print("The news is real")
else:
  print("The news is fake")

The news is real
